apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-controller-manager-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]  # Add permissions for pods
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-controller-manager-binding
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-controller-manager
    namespace: prometheus-operator-system
roleRef:
  kind: ClusterRole
  name: prometheus-operator-controller-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: prometheus-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: prometheus-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: carputopietro/metrics-collector:latest
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports: []
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          env:
            - name: MYSQL_USER
              value: "remote_user"  # Nome utente MySQL
            - name: MYSQL_PASSWORD
              value: "password"  # Password fissa
            - name: MYSQL_HOST
              value: "192.168.56.11"  # Indirizzo MySQL
            - name: MYSQL_PORT
              value: "3306"  # Porta MySQL
            - name: MYSQL_DATABASE
              value: "metricsdb"  # Nome del database
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
