# This rule is not used by the project prometheus-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over metrics.local.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/managed-by: kustomize
  name: metricscollector-admin-role
rules:
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors
  verbs:
  - '*'
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors/status
  verbs:
  - get
