# This rule is not used by the project prometheus-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the metrics.local.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/managed-by: kustomize
  name: metricscollector-editor-role
rules:
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors/status
  verbs:
  - get
