---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors/finalizers
  verbs:
  - update
- apiGroups:
  - metrics.local
  resources:
  - metricscollectors/status
  verbs:
  - get
  - patch
  - update
